In [1]:
import numpy as np
import tensorflow as tf

In [21]:
#np.eye(5)

In [38]:
x = tf.placeholder(shape=[None,None,None],dtype=tf.int32,name='x')

In [39]:
embedding = tf.constant(np.eye(5),dtype=tf.float32,name='embedding')

In [40]:
tf.nn.embedding_lookup?

In [41]:
embed_vec = tf.nn.embedding_lookup(embedding,x,name='lookup')

In [43]:
with tf.Session()  as sess:
    sample_x = np.array([[[0,2,1],[3,4,4]]])
    embed_val = sess.run(embed_vec,feed_dict={x:sample_x})
    print(embed_val.shape)
    print(embed_val)

(1, 2, 3, 5)
[[[[1. 0. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 1. 0. 0. 0.]]

  [[0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]
   [0. 0. 0. 0. 1.]]]]
